services:

  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  tempo:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "3200" # tempo
      - "4317" # otlp grpc
    depends_on:
      - init

  # Generate API traffic
  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6:/scripts
    command: run /scripts/script.js
    environment:
      - K6_OUT=json=stdout
    depends_on:
      - public-api
    networks:
      - default

  # And put them in an OTEL collector pipeline...
  otel-collector:
    image: otel/opentelemetry-collector:0.86.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    depends_on:
      - loki
      - prometheus
      - tempo

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.enable-otlp-receiver
      - --web.enable-lifecycle
      - --web.route-prefix=/
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.0.0
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d userdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./src/user-service
      dockerfile: Dockerfile
    ports:
      - "8080"
    volumes:
      - ./otel-agent/opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar
    environment:
      - JAVA_OPTS=-Xmx512m
      - OTEL_SERVICE_NAME=user-service
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_METRIC_EXPORT_INTERVAL=10000
      - OTEL_IMR_EXPORT_INTERVAL=10000
      - OTEL_INSTRUMENTATION_JVM_METRICS_ENABLED=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=userdb
      - DB_USER=user
      - DB_PASSWORD=password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      tempo:
        condition: service_started
      prometheus:
        condition: service_started
      loki:
        condition: service_started
      otel-collector:
        condition: service_started
    networks:
      - default

  public-api:
    build:
      context: ./src/public-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./otel-agent/opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar
    environment:
      - JAVA_OPTS=-Xmx512m
      - OTEL_SERVICE_NAME=public-api
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_METRIC_EXPORT_INTERVAL=10000
      - OTEL_IMR_EXPORT_INTERVAL=10000
      - OTEL_INSTRUMENTATION_JVM_METRICS_ENABLED=true
    depends_on:
      user-service:
        condition: service_healthy
      transaction-service:
        condition: service_healthy
      tempo:
        condition: service_started
      prometheus:
        condition: service_started
      loki:
        condition: service_started
      otel-collector:
        condition: service_started
    networks:
      - default

  transaction-service:
    build:
      context: ./src/transaction-service
      dockerfile: Dockerfile
    ports:
      - "8080"
    volumes:
      - ./otel-agent/opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar
    environment:
      - JAVA_OPTS=-Xmx512m
      - OTEL_SERVICE_NAME=transaction-service
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_METRIC_EXPORT_INTERVAL=10000
      - OTEL_IMR_EXPORT_INTERVAL=10000
      - OTEL_INSTRUMENTATION_JVM_METRICS_ENABLED=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=userdb
      - DB_USER=user
      - DB_PASSWORD=password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      tempo:
        condition: service_started
      prometheus:
        condition: service_started
      loki:
        condition: service_started
      otel-collector:
        condition: service_started
    networks:
      - default

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  kafka:
    image: observability-workshop-kafka:latest
    container_name: kafka
    build:
      context: .
      dockerfile: kafka/Dockerfile
    deploy:
      resources:
        limits:
          memory: 600M
    restart: unless-stopped
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_HEAP_OPTS=-Xmx400m -Xms400m
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      - OTEL_RESOURCE_ATTRIBUTES
      - OTEL_SERVICE_NAME=kafka
    healthcheck:
      test: nc -z kafka 9092
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - ./otel-agent/opentelemetry-javaagent.jar:/tmp/opentelemetry-javaagent.jar
    depends_on:
      otel-collector:
        condition: service_started
    networks:
      - default

  fraud-detection:
    build:
      context: ./src/fraud-detection-service
      dockerfile: Dockerfile
    environment:
      - KAFKA_ADDR=kafka:9092
      - JAVA_OPTS=-Xmx512m
      - OTEL_SERVICE_NAME=fraud-detection
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_METRIC_EXPORT_INTERVAL=10000
      - OTEL_IMR_EXPORT_INTERVAL=10000
      - OTEL_INSTRUMENTATION_JVM_METRICS_ENABLED=true
    volumes:
      - ./otel-agent/opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar
    depends_on:
      kafka:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - default

volumes:
  postgres_data: