database:
  host: ${DB_HOST:-localhost}
  port: ${DB_PORT:-5432}
  name: ${DB_NAME:-userdb}
  user: ${DB_USER:-user}
  password: ${DB_PASSWORD:-password}

kafka:
  bootstrapServers: ${KAFKA_ADDR:-localhost:9092}
  groupId: reconciliation-service
  topic: transactions 